# Generated by Django 4.0.3 on 2022-03-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
